AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy an EC2 instance for React Native Notes App

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c55b159cbfafe1f0  # Replace with your region's Ubuntu AMI ID
      KeyName: my-key-pair  # Replace with your actual key pair
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: ReactNativeNotesApp
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install -y nodejs npm
          sudo npm install -g pm2
          git clone https://github.com/saiyerubandi/react-native-notes-app.git /home/ubuntu/app
          cd /home/ubuntu/app
          npm install
          pm2 start App.js --name react-native-notes
          pm2 startup
          pm2 save

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
